### ISSUE TITLE
Judge assignment synchronization

### ISSUE THREAD

**Issue by nwf** [cmukgb/ctfws-timer-host#4]
Cross-reference https://github.com/cmukgb/ctfws-timer-web/issues/11 ; we should think about what we want the topic tree to look like, but as a strawman proposal, topic names `ctfws/game/judges/$ROLE[-$N]` (e.g. `ctfws/game/judges/wean-jail` or `ctfws/game/judges/dh-roaming-2`) and message body just free-form UTF-8 for human consumption.  The assignments are presumably not secret, so `ctfws/game` seems right.

As with most "database-y" things in MQTT, there isn't a great way to remove keys or to know when you've got all of them, but populating an initially empty sorted table as messages come in is probably fine.  I imagine we'd flush state and unsubscribe every time the user pages away from the display and resubscribe and rebuild it every time they came back.  Given the minimal amount of state, this seems like it should be fine.

**Comment by timparenti** [comment]
No need to involve the broker here, I think. This can be stored similarly to the Stuff-counting denominators, locally to the web app. Keep in mind that this all gets decided days ahead of time.
